# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Code2040API' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Code2040API
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'

end
